// !!!!!
// The file is generated by the codegen. Please do not edit by hand!
// !!!!!

export const SDL_APP_CONTINUE = 0;
export const SDL_APP_SUCCESS = 1;
export const SDL_APP_FAILURE = 2;
export const SDL_INIT_AUDIO = 16;
export const SDL_INIT_VIDEO = 32;
export const SDL_INIT_JOYSTICK = 512;
export const SDL_INIT_HAPTIC = 4096;
export const SDL_INIT_GAMEPAD = 8192;
export const SDL_INIT_EVENTS = 16384;
export const SDL_INIT_SENSOR = 32768;
export const SDL_INIT_CAMERA = 65536;
