export const enums: string[] = [
  "SDL_APP_CONTINUE",
  "SDL_APP_SUCCESS",
  "SDL_APP_FAILURE",

  "SDL_INIT_AUDIO",
  "SDL_INIT_VIDEO",
  "SDL_INIT_JOYSTICK",
  "SDL_INIT_HAPTIC",
  "SDL_INIT_GAMEPAD",
  "SDL_INIT_EVENTS",
  "SDL_INIT_SENSOR",
  "SDL_INIT_CAMERA",
] as const;
